# Generated by Django 5.2.4 on 2025-07-07 14:02

from django.db import migrations


def fill_in_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_flat_active_alter_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_in_new_building),
    ]
