# Generated by Django 5.2.4 on 2025-07-08 09:25

import re

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber
from phonenumber_field.phonenumber import to_python

DEFAULT_REGION = "RU"


def clean_phone_number(draft_number):
    if not draft_number:
        return None
    cleaned = re.sub(r'[^\d+]', '', draft_number)
    return cleaned


def migrate_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        draft_number = flat.owners_phonenumber
        cleaned_number = clean_phone_number(draft_number)
        if not cleaned_number:
            continue
        number = to_python(cleaned_number, region=DEFAULT_REGION)
        if number and number.is_valid():
            flat.owner_pure_phone = number
        else:
            flat.owner_pure_phone = None
        flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(migrate_phonenumbers)
    ]
