# Generated by Django 5.2.4 on 2025-07-08 11:31

from django.db import migrations


def move_data_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)


def reverse_move_data_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [
        migrations.RunPython(move_data_to_owner, reverse_move_data_to_owner)
    ]
