# Generated by Django 5.2.4 on 2025-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_migrate_phonenumbers'),
        ('property', '0014_migrate_phonenumbers_2'),
    ]

    operations = [
    ]
