# Generated by Django 5.2.4 on 2025-07-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_complaint_complaint_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_author',
            new_name='author',
        ),
    ]
