# Generated by Django 5.2.4 on 2025-07-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_owner_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
