# Generated by Django 5.2.4 on 2025-07-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_remove_flat_owner_remove_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
